### ISSUE TITLE
Error- write request banned

### ISSUE THREAD

**Issue by Puled** [GreptimeTeam/demo-scene#16]
I keep running into the following error:

` ERROR <module> Unhandled exception for futures: (MySQLdb.OperationalError) (1815, 'Write request banned for [Database] until [time UTC]`

I'm using a Windows 10 22H2 and use Windows Powershell to run 
`python agent.py`
as the command.

**Comment by tisonkun** [comment]
GreptimeCloud hobby plan has a rate limit since it's a shared resource poll for all the hobbyist.

I think we can ignore this error and wait for the time slice to retry. 

@shuiyisong @Puled IIRC the rate limit is >1000 qps, it should be generally large than your keyboard input frequency.

**Comment by shuiyisong** [comment]
@Puled Sorry for your inconvenience.
We happen to introduced a minor issue where CU limit is not correctly calculated yesterday. It should be fixed by now. Please try again and if there's any problem, do not hesitate to contact us.

Thank you for your patience.
