### ISSUE TITLE
[Bug] Monitor keyboard key combination exceptions on Windows systems

### ISSUE THREAD

**Issue by QuakeWang** [GreptimeTeam/demo-scene#2]
On Windows systems, monitor keyboard key combination exceptions. When using a key combination, ctrl + any letter key, the letter key is not displayed properly. It is normal to use keys like alt, or shift in combination with letters.

![image](https://github.com/GreptimeTeam/demo-scene/assets/45645138/d88bdc35-45bc-4bdc-8eab-6bcce22a08c2)

**Comment by tisonkun** [comment]
This seems to be an issue for https://github.com/moses-palmer/pynput/issues.

You can report there to improve the representation.

Instead, we'd probably add a transformer to improve the display string.

**Comment by tisonkun** [comment]
BTW when the modifier key changes the following key's semantic, it will display the effective key.

Said if you press `Shift` and `3`, you'd get: `Key.shift+'#'` instead of `Key.shift+'3'.

**Comment by tisonkun** [comment]
Closing ...

Not quite an issue of this repo. Perhaps pynput not the best but I don't find other library better.

**Comment by tisonkun** [comment]
Reported to pynput in https://github.com/moses-palmer/pynput/issues/591.
